Repository HeroGamers/MyDog, pull requests merged in 2022-10, with the labels that each got.

#48 Dogs sometimes lose their stats #44
  src/main/java/dk/fido2603/mydog/managers/TeleportationManager.java
Labels: bug

#49 Owners can`t accidentally hurt dogs
  src/main/java/dk/fido2603/mydog/listeners/DamageListener.java
Labels: enhancement

#53 Merge of Igzak/MyDog into DoggyCraft/MyDog
  .github/workflows/maven-publish.yml
  .github/workflows/maven-test.yml
  .github/workflows/maven.yml
  .gitignore
  .travis.yml
  README.md
  pom.xml
  src/dk/fido2603/mydog/Commands.java
  src/dk/fido2603/mydog/DogManager.java
  src/dk/fido2603/mydog/MyDog.java
  src/dk/fido2603/mydog/listeners/DamageListener.java
  src/dk/fido2603/mydog/listeners/WolfMainListener.java
  src/dk/fido2603/mydog/utils/ColorUtils.java
  src/main/java/dk/fido2603/mydog/MyDog.java
  src/main/java/dk/fido2603/mydog/api/MyDogAPI.java
  src/main/java/dk/fido2603/mydog/listeners/DamageListener.java
  src/main/java/dk/fido2603/mydog/listeners/WolfMainListener.java
  src/main/java/dk/fido2603/mydog/listeners/WolfMainListener_1_18.java
  src/main/java/dk/fido2603/mydog/managers/CommandManager.java
  src/main/java/dk/fido2603/mydog/managers/DogManager.java
  src/main/java/dk/fido2603/mydog/managers/PermissionsManager.java
  src/main/java/dk/fido2603/mydog/managers/TeleportationManager.java
  src/main/java/dk/fido2603/mydog/objects/Dog.java
  src/main/java/dk/fido2603/mydog/objects/LevelFactory.java
  src/main/java/dk/fido2603/mydog/utils/ColorUtils.java
  src/main/java/dk/fido2603/mydog/utils/ParticleUtils.java
  src/main/java/dk/fido2603/mydog/utils/TimeUtils.java
  src/main/java/dk/fido2603/mydog/utils/versioning/Tester.java
  src/main/java/dk/fido2603/mydog/utils/versioning/TesterFactory.java
  src/main/java/dk/fido2603/mydog/utils/versioning/Version.java
  src/main/java/dk/fido2603/mydog/utils/versioning/VersionFactory.java
  src/main/resources/plugin.yml
Labels: enhancement

#54 Merge of Igzak/MyDog into DoggyCraft/MyDog
  src/main/java/dk/fido2603/mydog/MyDog.java
  src/main/java/dk/fido2603/mydog/listeners/DamageListener.java
  src/main/java/dk/fido2603/mydog/listeners/WolfMainListener.java
  src/main/java/dk/fido2603/mydog/managers/CommandManager.java
  src/main/java/dk/fido2603/mydog/managers/DogManager.java
  src/main/java/dk/fido2603/mydog/managers/TeleportationManager.java
  src/main/java/dk/fido2603/mydog/objects/Dog.java
Labels: bug, enhancement

#55 Dead dog remake
  pom.xml
  src/main/java/dk/fido2603/mydog/MyDog.java
  src/main/java/dk/fido2603/mydog/api/MyDogAPI.java
  src/main/java/dk/fido2603/mydog/listeners/DamageListener.java
  src/main/java/dk/fido2603/mydog/listeners/WolfMainListener.java
  src/main/java/dk/fido2603/mydog/listeners/WolfMainListener_1_18.java
  src/main/java/dk/fido2603/mydog/managers/CommandManager.java
  src/main/java/dk/fido2603/mydog/managers/DogManager.java
  src/main/java/dk/fido2603/mydog/managers/PermissionsManager.java
  src/main/java/dk/fido2603/mydog/objects/Dog.java
  src/main/java/dk/fido2603/mydog/objects/LevelFactory.java
  src/main/java/dk/fido2603/mydog/utils/ColorUtils.java
  src/main/java/dk/fido2603/mydog/utils/ParticleUtils.java
  src/main/java/dk/fido2603/mydog/utils/TimeUtils.java
  src/main/java/dk/fido2603/mydog/utils/versioning/Tester.java
  src/main/java/dk/fido2603/mydog/utils/versioning/TesterFactory.java
  src/main/java/dk/fido2603/mydog/utils/versioning/Version.java
  src/main/java/dk/fido2603/mydog/utils/versioning/VersionFactory.java
Labels: enhancement

#56 Fixes a bug where correct damage values does not get applied when taming
  src/main/java/dk/fido2603/mydog/listeners/DamageListener.java
  src/main/java/dk/fido2603/mydog/listeners/WolfMainListener.java
  src/main/java/dk/fido2603/mydog/objects/Dog.java
Labels: bug

#58 v0.1.4 Candidate Release
  pom.xml
  src/main/java/dk/fido2603/mydog/MyDog.java
  src/main/java/dk/fido2603/mydog/api/MyDogAPI.java
  src/main/java/dk/fido2603/mydog/listeners/DamageListener.java
  src/main/java/dk/fido2603/mydog/listeners/WolfMainListener.java
  src/main/java/dk/fido2603/mydog/listeners/WolfMainListener_1_18.java
  src/main/java/dk/fido2603/mydog/managers/CommandManager.java
  src/main/java/dk/fido2603/mydog/managers/DogManager.java
  src/main/java/dk/fido2603/mydog/managers/PermissionsManager.java
  src/main/java/dk/fido2603/mydog/objects/Dog.java
  src/main/java/dk/fido2603/mydog/objects/LevelFactory.java
  src/main/java/dk/fido2603/mydog/utils/ColorUtils.java
  src/main/java/dk/fido2603/mydog/utils/ParticleUtils.java
  src/main/java/dk/fido2603/mydog/utils/TimeUtils.java
  src/main/java/dk/fido2603/mydog/utils/versioning/Tester.java
  src/main/java/dk/fido2603/mydog/utils/versioning/TesterFactory.java
  src/main/java/dk/fido2603/mydog/utils/versioning/Version.java
  src/main/java/dk/fido2603/mydog/utils/versioning/VersionFactory.java
Labels: enhancement
